config/routes.rb
Rails.application.routes.draw do
  resources :tests

  resources :patients

  devise_for :employees
  get 'principal' => 'record#index' , as: :student_index
  get 'alumnocomun' => 'record#comun' , as: :comun_student

  get 'record/worker'
  post 'guardar_estudiante' => 'record#create' , as: :create_student

end

app/models/business.rb
class Business < ActiveRecord::Base
	has_many :students
end

app/models/course.rb
class Course < ActiveRecord::Base
	has_many :detail_courses
	has_many :students, through: :detail_courses
end

app/models/detail_course.rb
class DetailCourse < ActiveRecord::Base
  belongs_to :student
  belongs_to :course
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/patient.rb
class Patient < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base
	has_many :detail_courses, dependent: :destroy
	has_many :courses, through: :detail_courses
	before_save :up_full_name

	validates :name, :paternal, :maternal, :dni, :years ,presence: {message: 'no puede estar en blanco'}
	validates :sex , inclusion: {in: [true,false], message: 'tiene valores no aceptables.'}
	validates :dni, :phone,numericality: {message: 'no es un numero'}
	validates :dni, uniqueness: {message: 'ya existe'}
	validates :dni, length: {is: 8, message: 'tiene numero errado de caracteres'}
	def full_name
		paternal.to_s + "" + maternal.to_s + "" + name.to_s
	end
	def up_full_name
		self.name = self.name.upcase
		self.paternal = self.paternal.upcase
		self.maternal = self.maternal.upcase
	end
end

app/models/teaching.rb
class Teaching < ActiveRecord::Base
	validates :name, presence: true
	has_many :courses
end

app/models/test.rb
class Test < ActiveRecord::Base
  belongs_to :patient
end

app/models/type_course.rb
class TypeCourse < ActiveRecord::Base
	has_many :courses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @patients = Patient.all
    respond_with(@patients)
  end

  def show
    respond_with(@patient)
  end

  def new
    @patient = Patient.new
    respond_with(@patient)
  end

  def edit
  end

  def create
    @patient = Patient.new(patient_params)
    @patient.save
    respond_with(@patient)
  end

  def update
    @patient.update(patient_params)
    respond_with(@patient)
  end

  def destroy
    @patient.destroy
    respond_with(@patient)
  end

  private
    def set_patient
      @patient = Patient.find(params[:id])
    end

    def patient_params
      params.require(:patient).permit(:name, :dni, :phone, :home)
    end
end

app/controllers/record_controller.rb
class RecordController < ApplicationController
	before_action :set_patient, only: [:update, :delete]
	def comun
	end

	def index
	end
	def create
		@student = Student.new(student_params)
		@student.save
		respond_to do |format|
			format.html {render text: params}
			format.js
		end
	end
	private
	def student_params
		params.require(:student).permit(:name, :paternal, :maternal, :dni, :sex, :address, :years, :phone)
	end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :set_test, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @tests = Test.all
    respond_with(@tests)
  end

  def show
    respond_with(@test)
  end

  def new
    @test = Test.new
    respond_with(@test)
  end

  def edit
  end

  def create
    @test = Test.new(test_params)
    @test.save
    respond_with(@test)
  end

  def update
    @test.update(test_params)
    respond_with(@test)
  end

  def destroy
    @test.destroy
    respond_with(@test)
  end

  private
    def set_test
      @test = Test.find(params[:id])
    end

    def test_params
      params.require(:test).permit(:history_clinic, :patient_id, :occupational, :enfermedad)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/record_helper.rb
module RecordHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Academia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="row-fluid">

<nav class="navbar navbar-default " role="navigation">
  <!-- El logotipo y el icono que despliega el menú se agrupan
       para mostrarlos mejor en los dispositivos móviles -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse"
            data-target=".navbar-ex1-collapse">
      <span class="sr-only">Desplegar navegación</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#"><span class="glyphicon glyphicon-align-justify"></span></a>
  </div>
 
  <!-- Agrupar los enlaces de navegación, los formularios y cualquier
       otro elemento que se pueda ocultar al minimizar la barra -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li><a href="#">Quienes Somos</a></li>
      <li><a href="#">Cursos</a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Ingresar<b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to 'Alumno comun', comun_student_path %></li>
          <li><a href="#">Trabajador</a></li>
          <li><a href="#">Chat</a></li>
          <li class="divider"></li>
          <li><a href="#"></a></li>
          <li class="divider"></li>
          <li><a href="#">Acción #5</a></li>
        </ul>
      </li>
    </ul>
 
    
 
    <ul class="nav navbar-nav navbar-right">
      
      <form class="navbar-form navbar-left" role="search">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Buscar">
      </div>
      <button type="submit" class="btn btn-default">Enviar</button>
    </form>
    <li><%= link_to 'Registrarse', new_employee_registration_path %></li>
    <li><%= link_to 'Iniciar Sesion', new_employee_session_path %></li>
       <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Jeison <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><a href="#">Preguntas Frecuentes</a></li>
          <li><a href="#">Contactenos</a></li>
          <li class="divider"></li>
          <li><%= link_to 'salir',  destroy_employee_session_path , method: 'delete' %></li>
        </ul>
      </li>
    </ul>
  </div>
</nav>
   <% flash.each do |name, msg| %>
        <% content_tag(:div, msg , class: 'alert alert-#(name)')%>
   <% end %>
<div class="container">
    <div class="row row-offcanvas row-offcanvas-right">
      <%= yield %>
    </div>    
  </div>

</body>
</html>

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :dni %><br>
    <%= f.text_field :dni %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :home %><br>
    <%= f.text_field :home %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<h1>Listing patients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Dni</th>
      <th>Phone</th>
      <th>Home</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.name %></td>
        <td><%= patient.dni %></td>
        <td><%= patient.phone %></td>
        <td><%= patient.home %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>New patient</h1>

<%= render 'form' %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @patient.name %>
</p>

<p>
  <strong>Dni:</strong>
  <%= @patient.dni %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @patient.phone %>
</p>

<p>
  <strong>Home:</strong>
  <%= @patient.home %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>

app/views/record/_form.html.erb
<%= form_tag(create_student_path,method: 'post',role: 'form', remote: true) do %>

<div class="row-fluid">
    
    <div class="form-group">
        <%= label :student, :name, 'Nombres' %>
        <%= text_field :student, :name ,class: 'form-control'%>
    </div>
    <div class="form-group">
        <%= label_tag :paternal, 'Apellidos '%>
        <%= text_field :student ,:paternal, class: 'form-control' , placeholder: 'Paterno'%> <br> 
        <%= text_field_tag :student , :maternal, class: 'form-control' , placeholder: 'Maternal'%>
    </div>
    <div class="form-group">
        <%= label_tag :dni, 'DNI '%>
        <%= text_field :patient, :dni, class: 'form-control'%>
    </div>
    <div class="form-group">
        <%= label_tag :years, 'Edad'%>
        <%= text_field_tag :years , '', class: 'form-control' , placeholder: 'edad'%>
    </div>
    <div class="form-group">
        <%= label_tag :address, 'direccion'%>
        <%= text_field :student, :address , class: 'form-control' , placeholder: 'direccion'%>
    </div>
    <div class="form-group">
        <%= label :student, :sex , 'Masculino', :value =>"true"%>
        <%= radio_button :student,:sex , true %>
        <br>
        <%= label :student , :sex, 'Femenino', :value => "false" %>
        <%= radio_button :student, :sex ,false %>
    </div>
    <div class="form-group">
        <%= label_tag :mail, 'Correo'%>
        <%= text_field :student , :mail, class: 'form-control' , placeholder: 'correo'%>
    </div>
    <div class="form-group">
        <%= label_tag :phone, 'Telefono'%>
        <%= text_field_tag :student, :phone, class: 'form-control' , placeholder: 'telefono'%>
    </div>
    <div class="text-center top-buffer">
    <%= button_tag type: 'submit', class: "btn btn-success text-center" do %>
    Guardar <span class="glyphicon glyphicon-floppy-disk"></span>
    <% end %>
    </div>
<% end %>

app/views/record/_table.html.erb
<table class="table  table-striped">
	<thead>
		<tr>
			<td></td>
			<td>#</td>
			<td>Nombre</td>
			<td>Telefono</td>
			<td>Edad</td>
			<td>Sexo</td>
			<td>Examenes</td>
			<td>Nuevo</td>
		</tr>
	</thead>
	<tbody>
		
		<tr>
			
			<td>id</td>
			<td>dni</td>
			<td>telefono</td>
			
			
			<td>
				
			</td>
			
			<td>
				<div class="modal fade" id="" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
					<div class="modal-dialog">
						<div class="modal-content">
							<div class="modal-header">
								<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
								<h4 class="modal-title" id="myModalLabel"><center><b>INGRESAR PACIENTE</b></center></h4>
							</div>
							<div class="modal-body">
								
							</div>
						</div>
					</div>
				</div>
			</td>
		</tr>
		
	</tbody>
</table>

app/views/record/comun.html.erb
<div class="row-fluid">
  <div class="col-md-4" ></div>
  <div class="col-md-4" >
    <div class="jumbotron">
      <div class="container">
        <%= form_tag(comun_student_path , method: 'post') do %>
    <div class="form-group">
        <%= label_tag :name, 'Nombres'%>
        <%= text_field_tag :name , '', class: 'form-control' , placeholder: 'Nombres'%>
    </div>
    <div class="form-group">
        <%= label_tag :apellido, 'Apellidos '%>
        <%= text_field_tag :paterno , '', class: 'form-control' , placeholder: 'Paterno'%> <br> 
        <%= text_field_tag :materno , '', class: 'form-control' , placeholder: 'Maternal'%>
    </div>
     <div class="form-group">
        <%= label_tag :dni, 'DNI '%>
        <%= text_field_tag :dni , '', class: 'form-control' , placeholder: 'dni'%>
    </div>
    <div class="form-group">
        <%= label_tag :edad, 'Edad'%>
        <%= text_field_tag :edad , '', class: 'form-control' , placeholder: 'edad'%>
    </div>
    <div class="form-group">
        <%= label_tag :direccion, 'direccion'%>
        <%= text_field_tag :direccion , '', class: 'form-control' , placeholder: 'direccion'%>
    </div>
    <div class="form-group">
        <%= label_tag :mail, 'Correo'%>
        <%= text_field_tag :mail , '', class: 'form-control' , placeholder: 'correo'%>
    </div>
    <div class="form-group">
        <%= label_tag :telefono, 'Telefono'%>
        <%= text_field_tag :telefono , '', class: 'form-control' , placeholder: 'telefono'%>
    </div>
   <%= submit_tag 'Enviar',class: 'btn btn-primary'%>
   <% end %>
    </div>
  </div>
  
</div> 

app/views/record/create.js.erb
if ('<%= @student.errors.any? %>' == 'true') {
	var messages = '<%= @student.errors.full_messages %>';
	alert(messages);	
}
else{
	alert('alumno ingresado con éxito, DNI: <%= @student.dni %>');
	$('#table').html("<%= j (render 'table' )%>");
}

app/views/record/index.html.erb
<div class="text-center">
	<h1>SISTEMA DE REGISTRO	</h1>
</div>
<div class="row top-buffer">
	<div class="col-md-12">
		<div class="row">
			<div class="form-group">
				<%= form_tag(student_index_path, method: 'get', role: 'form') do %>
				<div class="col-md-4">
					<%= text_field_tag :paternal, '', {class: 'form-control', placeholder: 'Apellido paterno'} %>
				</div>
				<div class="col-md-4">
					<%= text_field_tag :maternal, '', {class: 'form-control', placeholder: 'Apellido materno'} %>
				</div>
				<div class="col-md-2">
					<%= submit_tag 'Buscar', class: 'btn' %>
				</div>
				<div class="col-md-2">
					<button type="button" class="btn btn-primary " data-toggle="modal" data-target="#modal_create_student">Nuevo Alumno <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
					</button>
				</div>
				<% end %>
			</div>
		</div>

	</div>
	<div class=""></div>
</div>
<div id="table">
	<%= render 'table' %>
</div>
<div class="col-md-8">
	<div class="modal fade" id="modal_create_student" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title" id="myModalLabel"><center><b>INGRESAR ALUMNO</b></center></h4>
				</div>
				<div class="modal-body">
					<%= render 'form' %>
				</div>
			</div>
		</div>
	</div>
</div>